import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const LanguageContext = createContext(null)

const translations = {
  ca: {
    sessionStarted: 'Sessió iniciada',
    selectLanguage: 'Seleccionar idioma',
    logout: 'Logout',
    dashboard: 'Dashboard',
    device: 'Dispositiu',
    devices: 'Dispositius',
    sensors: 'Sensors',
    installations: 'Instal·lacions',
    plants: 'Plantes',
    readings: 'Lectures',
    users: 'Usuaris',
    alerts: 'Alertes',
    settings: 'Configuració',
    clients: 'Clients',
    operations: 'Operativa',
    data: 'Dades',
    administration: 'Administració',
    dashboardTitle: 'Visió general de Greenlytics',
    dashboardSubtitle: 'Estat actual de plantes, sensors i lectures reals de la plataforma.',
    dashboardLoading: 'Carregant dades reals del dashboard...',
    dashboardLoadError: 'No s’han pogut carregar les dades del dashboard.',
    viewAlerts: 'Veure alertes',
    addSensor: 'Afegir sensor',
    readingTrends: 'Tendències de lectures',
    readingTrendsDescription: 'Humitat del sòl i llum de les últimes lectures disponibles.',
    readingTrendsEmpty: 'Encara no hi ha prou dades per mostrar la gràfica.',
    plantStatus: 'Estat de les plantes',
    plantStatusDescription: 'Resum ràpid per planta o sensor, amb l’últim valor disponible.',
    plantStatusEmpty: 'No hi ha plantes o sensors amb dades per mostrar encara.',
    criticalCount: 'Crítiques:',
    lastReading: 'Última lectura:',
    noData: 'Sense dades',
    soilHumidity: 'Humitat terra',
    lightRaw: 'Llum (raw)',
    temperature: 'Temperatura',
    mostRecentData: 'Dada més recent',
    light: 'Llum',
    rawValue: 'Valor raw',
    rainRssi: 'Pluja / RSSI',
    rainYes: 'Plou',
    rainNo: 'Sec',
    noRssi: 'Sense RSSI',
'dashboardKpi.totalPlants.title': 'Plantes totals',
'dashboardKpi.totalPlants.subtitle': 'Plantes registrades',
'dashboardKpi.activePlants.title': 'Plantes actives',
'dashboardKpi.activePlants.subtitle': 'En seguiment',
'dashboardKpi.onlineSensors.title': 'Sensors online',
'dashboardKpi.onlineSensors.subtitle': 'Segons el camp status',
'dashboardKpi.recentReadings.title': 'Lectures recents',
'dashboardKpi.recentReadings.subtitle': 'Últims registres disponibles',

    client: 'Client',
    clientDetail: 'Detall de client',
    newClient: 'Nou client',
    newClientDescription: 'Crea un nou client de la plataforma.',
    clientDetailDescription: 'Consulta i actualitza la informació del client.',
    backToList: 'Tornar al llistat',

    clientTabGeneral: 'Informació general',
    clientTabBranding: 'Branding',
    clientTabUsers: 'Usuaris',

    clientGeneralInfo: 'Informació general',
    clientAdditionalInfo: 'Informació addicional',
    clientBrandingMvp: 'Branding MVP',
    clientUsersTitle: 'Usuaris del client',
    clientUsersPlaceholder: 'Gestiona els usuaris vinculats a aquest client.',
    loadingClient: 'Carregant client...',
    clientLoadError: 'No s’ha pogut carregar el client.',
    clientSaveError: 'No s’ha pogut desar el client.',
    clientSavedSuccess: 'Client actualitzat correctament.',
    clientValidationLegalName: 'El camp "Nom legal" és obligatori.',
    clientValidationTradeName: 'El camp "Nom comercial" és obligatori.',
    clientValidationTaxId: 'El camp "Tax ID" és obligatori.',
    clientValidationEmail: 'El camp "Email" és obligatori.',
    clientValidationPhone: 'El camp "Telèfon" és obligatori.',
    clientValidationClientType: 'El camp "Tipus client" és obligatori.',
    clientValidationApiSecret: 'El camp "Api secret" és obligatori a l’alta.',
    clientCodeAutoHint: 'Es generarà automàticament en desar.',
    automatic: 'Automàtic',
    unnamed: 'Sense nom',
    noEmail: 'Sense email',
    yes: 'Sí',
    no: 'No',
    brandPreview: 'Preview de marca',
    example: 'Exemple',
    legalName: 'Nom legal',
    tradeName: 'Nom comercial',
    taxId: 'Tax ID',
    taxIdPlaceholder: 'NIF / CIF',
    email: 'Email',
    phone: 'Telèfon',
    clientType: 'Tipus client',
    active: 'Actiu',
    activeClient: 'Client actiu',
    apiSecret: 'Api secret',
    apiSecretCreateOnly: 'Només s’informa a l’alta del client.',
    apiSecretPlaceholder: 'Secret per generar hash',
    website: 'Website',
    externalId: 'External ID',
    address: 'Adreça',
    city: 'Ciutat',
    stateProvince: 'Província / Estat',
    postalCode: 'Codi postal',
    country: 'País',
    notes: 'Notes',
    appName: 'Nom de l’aplicació',
    appNamePlaceholder: 'Ex. Agro Monitor',
    logoUrl: 'Logo URL',
    faviconUrl: 'Favicon URL',
    primaryColor: 'Color primari',
    secondaryColor: 'Color secundari',
    saving: 'Desant...',
    createClient: 'Crear client',
    saveChanges: 'Desar canvis',
    cancel: 'Cancel·lar',
    code: 'Codi',

    clientUsersSectionTitle: 'Usuaris del client',
    clientUsersSectionDescription: 'Només es poden crear usuaris MANAGER o VIEWER. L’email no es pot repetir dins del mateix client.',
    newUser: 'Nou usuari',
    editUser: 'Editar usuari',
    username: 'Username',
    firstName: 'Nom',
    lastName: 'Cognoms',
    role: 'Rol',
    status: 'Estat',
    actions: 'Accions',
    open: 'Obrir',
    close: 'Tancar',
    saveUser: 'Desar usuari',
    createUser: 'Crear usuari',
    activeUser: 'Usuari actiu',
    password: 'Password',
    passwordEditHint: 'Deixa-ho en blanc si no vols canviar-la.',
    noUsersFound: 'No s’han trobat usuaris per a aquest client.',
    loadingUsers: 'Carregant usuaris...',
    loadingRoles: 'Carregant rols...',
    userSavedSuccess: 'Usuari desat correctament.',
    userSaveError: 'No s’ha pogut desar l’usuari.',
    userLoadError: 'No s’han pogut carregar els usuaris del client.',
    usersAvailableAfterSaveClient: 'Primer has de desar el client per poder gestionar-ne els usuaris.',
    roleManager: 'Manager',
    roleViewer: 'Viewer',
    validationUsernameRequired: 'El camp "Username" és obligatori.',
    validationUserEmailRequired: 'El camp "Email" és obligatori.',
    validationFirstNameRequired: 'El camp "Nom" és obligatori.',
    validationRoleRequired: 'El camp "Rol" és obligatori.',
    validationPasswordRequired: 'El camp "Password" és obligatori a l’alta.',
  },
  es: {
    sessionStarted: 'Sesión iniciada',
    selectLanguage: 'Seleccionar idioma',
    logout: 'Logout',
    dashboard: 'Dashboard',
    device: 'Dispositivo',
    devices: 'Dispositivos',
    sensors: 'Sensores',
    installations: 'Instalaciones',
    plants: 'Plantas',
    readings: 'Lecturas',
    users: 'Usuarios',
    alerts: 'Alertas',
    settings: 'Configuración',
    clients: 'Clientes',
    operations: 'Operativa',
    data: 'Datos',
    administration: 'Administración',
    dashboardTitle: 'Visión general de Greenlytics',
    dashboardSubtitle: 'Estado actual de plantas, sensores y lecturas reales de la plataforma.',
    dashboardLoading: 'Cargando datos reales del dashboard...',
    dashboardLoadError: 'No se han podido cargar los datos del dashboard.',
    viewAlerts: 'Ver alertas',
    addSensor: 'Añadir sensor',
    readingTrends: 'Tendencias de lecturas',
    readingTrendsDescription: 'Humedad del suelo y luz de las últimas lecturas disponibles.',
    readingTrendsEmpty: 'Todavía no hay suficientes datos para mostrar la gráfica.',
    plantStatus: 'Estado de las plantas',
    plantStatusDescription: 'Resumen rápido por planta o sensor, con el último valor disponible.',
    plantStatusEmpty: 'No hay plantas o sensores con datos para mostrar todavía.',
    criticalCount: 'Críticas:',
    lastReading: 'Última lectura:',
    noData: 'Sin datos',
    soilHumidity: 'Humedad suelo',
    lightRaw: 'Luz (raw)',
    temperature: 'Temperatura',
    mostRecentData: 'Dato más reciente',
    light: 'Luz',
    rawValue: 'Valor raw',
    rainRssi: 'Lluvia / RSSI',
    rainYes: 'Llueve',
    rainNo: 'Seco',
    noRssi: 'Sin RSSI',
'dashboardKpi.totalPlants.title': 'Plantas totales',
'dashboardKpi.totalPlants.subtitle': 'Plantas registradas',
'dashboardKpi.activePlants.title': 'Plantas activas',
'dashboardKpi.activePlants.subtitle': 'En seguimento',
'dashboardKpi.onlineSensors.title': 'Sensores online',
'dashboardKpi.onlineSensors.subtitle': 'Segons el camp status',
'dashboardKpi.recentReadings.title': 'Lecturas recientes',
'dashboardKpi.recentReadings.subtitle': 'Últimos registros disponibles',

    administration: 'Administración',
    client: 'Cliente',
    clientDetail: 'Detalle de cliente',
    newClient: 'Nuevo cliente',
    newClientDescription: 'Crea un nuevo cliente de la plataforma.',
    clientDetailDescription: 'Consulta y actualiza la información del cliente.',
    backToList: 'Volver al listado',

    clientTabGeneral: 'Información general',
    clientTabBranding: 'Branding',
    clientTabUsers: 'Usuarios',

    clientGeneralInfo: 'Información general',
    clientAdditionalInfo: 'Información adicional',
    clientBrandingMvp: 'Branding MVP',
    clientUsersTitle: 'Usuarios del cliente',
    clientUsersPlaceholder: 'Gestiona los usuarios vinculados a este cliente.',
    loadingClient: 'Cargando cliente...',
    clientLoadError: 'No se ha podido cargar el cliente.',
    clientSaveError: 'No se ha podido guardar el cliente.',
    clientSavedSuccess: 'Cliente actualizado correctamente.',
    clientValidationLegalName: 'El campo "Nombre legal" es obligatorio.',
    clientValidationTradeName: 'El campo "Nombre comercial" es obligatorio.',
    clientValidationTaxId: 'El campo "Tax ID" es obligatorio.',
    clientValidationEmail: 'El campo "Email" es obligatorio.',
    clientValidationPhone: 'El campo "Teléfono" es obligatorio.',
    clientValidationClientType: 'El campo "Tipo de cliente" es obligatorio.',
    clientValidationApiSecret: 'El campo "Api secret" es obligatorio en el alta.',
    clientCodeAutoHint: 'Se generará automáticamente al guardar.',
    automatic: 'Automático',
    unnamed: 'Sin nombre',
    noEmail: 'Sin email',
    yes: 'Sí',
    no: 'No',
    brandPreview: 'Preview de marca',
    example: 'Ejemplo',
    legalName: 'Nombre legal',
    tradeName: 'Nombre comercial',
    taxId: 'Tax ID',
    taxIdPlaceholder: 'NIF / CIF',
    email: 'Email',
    phone: 'Teléfono',
    clientType: 'Tipo de cliente',
    active: 'Activo',
    activeClient: 'Cliente activo',
    apiSecret: 'Api secret',
    apiSecretCreateOnly: 'Solo se informa en el alta del cliente.',
    apiSecretPlaceholder: 'Secret para generar hash',
    website: 'Website',
    externalId: 'External ID',
    address: 'Dirección',
    city: 'Ciudad',
    stateProvince: 'Provincia / Estado',
    postalCode: 'Código postal',
    country: 'País',
    notes: 'Notas',
    appName: 'Nombre de la aplicación',
    appNamePlaceholder: 'Ej. Agro Monitor',
    logoUrl: 'Logo URL',
    faviconUrl: 'Favicon URL',
    primaryColor: 'Color primario',
    secondaryColor: 'Color secundario',
    saving: 'Guardando...',
    createClient: 'Crear cliente',
    saveChanges: 'Guardar cambios',
    cancel: 'Cancelar',
    code: 'Código',

    clientUsersSectionTitle: 'Usuarios del cliente',
    clientUsersSectionDescription: 'Solo se pueden crear usuarios MANAGER o VIEWER. El email no se puede repetir dentro del mismo cliente.',
    newUser: 'Nuevo usuario',
    editUser: 'Editar usuario',
    username: 'Username',
    firstName: 'Nombre',
    lastName: 'Apellidos',
    role: 'Rol',
    status: 'Estado',
    actions: 'Acciones',
    open: 'Abrir',
    close: 'Cerrar',
    saveUser: 'Guardar usuario',
    createUser: 'Crear usuario',
    activeUser: 'Usuario activo',
    password: 'Password',
    passwordEditHint: 'Déjalo vacío si no quieres cambiarla.',
    noUsersFound: 'No se han encontrado usuarios para este cliente.',
    loadingUsers: 'Cargando usuarios...',
    loadingRoles: 'Cargando roles...',
    userSavedSuccess: 'Usuario guardado correctamente.',
    userSaveError: 'No se ha podido guardar el usuario.',
    userLoadError: 'No se han podido cargar los usuarios del cliente.',
    usersAvailableAfterSaveClient: 'Primero debes guardar el cliente para poder gestionar sus usuarios.',
    roleManager: 'Manager',
    roleViewer: 'Viewer',
    validationUsernameRequired: 'El campo "Username" es obligatorio.',
    validationUserEmailRequired: 'El campo "Email" es obligatorio.',
    validationFirstNameRequired: 'El campo "Nombre" es obligatorio.',
    validationRoleRequired: 'El campo "Rol" es obligatorio.',
    validationPasswordRequired: 'El campo "Password" es obligatorio en el alta.',
  },
  en: {
    sessionStarted: 'Session started',
    selectLanguage: 'Select language',
    logout: 'Logout',
    dashboard: 'Dashboard',
    device: 'Device',
    devices: 'Devices',
    sensors: 'Sensors',
    installations: 'Installations',
    plants: 'Plants',
    readings: 'Readings',
    users: 'Users',
    alerts: 'Alerts',
    settings: 'Settings',
    clients: 'Clients',
    operations: 'Operations',
    data: 'Data',
    administration: 'Administration',
    dashboardTitle: 'Greenlytics overview',
    dashboardSubtitle: 'Current status of plants, sensors and real platform readings.',
    dashboardLoading: 'Loading real dashboard data...',
    dashboardLoadError: 'Could not load dashboard data.',
    viewAlerts: 'View alerts',
    addSensor: 'Add sensor',
    readingTrends: 'Reading trends',
    readingTrendsDescription: 'Soil humidity and light from the latest available readings.',
    readingTrendsEmpty: 'There is not enough data yet to display the chart.',
    plantStatus: 'Plant status',
    plantStatusDescription: 'Quick summary by plant or sensor, with the latest available value.',
    plantStatusEmpty: 'There are no plants or sensors with data to display yet.',
    criticalCount: 'Critical:',
    lastReading: 'Last reading:',
    noData: 'No data',
    soilHumidity: 'Soil humidity',
    lightRaw: 'Light (raw)',
    temperature: 'Temperature',
    mostRecentData: 'Most recent data',
    light: 'Light',
    rawValue: 'Raw value',
    rainRssi: 'Rain / RSSI',
    rainYes: 'Raining',
    rainNo: 'Dry',
    noRssi: 'No RSSI',

'dashboardKpi.totalPlants.title': 'Total plants',
'dashboardKpi.totalPlants.subtitle': 'Registered plants',
'dashboardKpi.activePlants.title': 'Active plants',
'dashboardKpi.activePlants.subtitle': 'Under monitoring',
'dashboardKpi.onlineSensors.title': 'Sensors online',
'dashboardKpi.onlineSensors.subtitle': 'Based on the status field',
'dashboardKpi.recentReadings.title': 'Recent readings',
'dashboardKpi.recentReadings.subtitle': 'Latest available records',
   
    client: 'Client',
    clientDetail: 'Client detail',
    newClient: 'New client',
    newClientDescription: 'Create a new platform client.',
    clientDetailDescription: 'Review and update the client information.',
    backToList: 'Back to list',

    clientTabGeneral: 'General information',
    clientTabBranding: 'Branding',
    clientTabUsers: 'Users',

    clientGeneralInfo: 'General information',
    clientAdditionalInfo: 'Additional information',
    clientBrandingMvp: 'Branding MVP',
    clientUsersTitle: 'Client users',
    clientUsersPlaceholder: 'Manage the users linked to this client.',
    loadingClient: 'Loading client...',
    clientLoadError: 'Could not load client.',
    clientSaveError: 'Could not save client.',
    clientSavedSuccess: 'Client updated successfully.',
    clientValidationLegalName: 'The "Legal name" field is required.',
    clientValidationTradeName: 'The "Trade name" field is required.',
    clientValidationTaxId: 'The "Tax ID" field is required.',
    clientValidationEmail: 'The "Email" field is required.',
    clientValidationPhone: 'The "Phone" field is required.',
    clientValidationClientType: 'The "Client type" field is required.',
    clientValidationApiSecret: 'The "Api secret" field is required on create.',
    clientCodeAutoHint: 'It will be generated automatically when saving.',
    automatic: 'Automatic',
    unnamed: 'Unnamed',
    noEmail: 'No email',
    yes: 'Yes',
    no: 'No',
    brandPreview: 'Brand preview',
    example: 'Example',
    legalName: 'Legal name',
    tradeName: 'Trade name',
    taxId: 'Tax ID',
    taxIdPlaceholder: 'VAT / Tax ID',
    email: 'Email',
    phone: 'Phone',
    clientType: 'Client type',
    active: 'Active',
    activeClient: 'Active client',
    apiSecret: 'Api secret',
    apiSecretCreateOnly: 'Only informed when creating the client.',
    apiSecretPlaceholder: 'Secret to generate hash',
    website: 'Website',
    externalId: 'External ID',
    address: 'Address',
    city: 'City',
    stateProvince: 'State / Province',
    postalCode: 'Postal code',
    country: 'Country',
    notes: 'Notes',
    appName: 'Application name',
    appNamePlaceholder: 'Ex. Agro Monitor',
    logoUrl: 'Logo URL',
    faviconUrl: 'Favicon URL',
    primaryColor: 'Primary color',
    secondaryColor: 'Secondary color',
    saving: 'Saving...',
    createClient: 'Create client',
    saveChanges: 'Save changes',
    cancel: 'Cancel',
    code: 'Code',

    clientUsersSectionTitle: 'Client users',
    clientUsersSectionDescription: 'Only MANAGER or VIEWER users can be created. Email cannot be duplicated within the same client.',
    newUser: 'New user',
    editUser: 'Edit user',
    username: 'Username',
    firstName: 'First name',
    lastName: 'Last name',
    role: 'Role',
    status: 'Status',
    actions: 'Actions',
    open: 'Open',
    close: 'Close',
    saveUser: 'Save user',
    createUser: 'Create user',
    activeUser: 'Active user',
    password: 'Password',
    passwordEditHint: 'Leave it blank if you do not want to change it.',
    noUsersFound: 'No users found for this client.',
    loadingUsers: 'Loading users...',
    loadingRoles: 'Loading roles...',
    userSavedSuccess: 'User saved successfully.',
    userSaveError: 'Could not save user.',
    userLoadError: 'Could not load client users.',
    usersAvailableAfterSaveClient: 'You need to save the client first to manage its users.',
    roleManager: 'Manager',
    roleViewer: 'Viewer',
    validationUsernameRequired: 'The "Username" field is required.',
    validationUserEmailRequired: 'The "Email" field is required.',
    validationFirstNameRequired: 'The "First name" field is required.',
    validationRoleRequired: 'The "Role" field is required.',
    validationPasswordRequired: 'The "Password" field is required on create.',
  },
}

const STORAGE_KEY = 'greenlytics_language'

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem(STORAGE_KEY) || 'ca')

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const value = useMemo(() => {
    const dict = translations[language] || translations.ca
    return {
      language,
      setLanguage,
      t: (key) => dict[key] || key,
    }
  }, [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)

  if (!context) {
    throw new Error('useLanguage s’ha d’utilitzar dins de LanguageProvider')
  }

  return context
}
